# Generated by Django 4.0.1 on 2022-05-03 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_applyjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skills',
        ),
    ]
