# Generated by Django 4.0.1 on 2022-05-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_remove_job_description_remove_job_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='creationdate',
        ),
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
