# Generated by Django 4.0.1 on 2022-05-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_remove_job_creationdate_alter_job_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyjob',
            old_name='fname',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='applyjob',
            old_name='lname',
            new_name='i_name',
        ),
        migrations.RemoveField(
            model_name='applyjob',
            name='mobile',
        ),
        migrations.AddField(
            model_name='applyjob',
            name='p_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='num',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
