# Generated by Django 4.0.1 on 2022-05-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_rename_fname_applyjob_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyjob',
            old_name='contact',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='applyjob',
            old_name='i_name',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='applyjob',
            old_name='p_name',
            new_name='mobile',
        ),
    ]
